# Generated by Django 4.2.5 on 2023-09-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('duration', models.DurationField()),
                ('date_released', models.DateField()),
                ('average_rating_out_of_five', models.FloatField()),
            ],
            options={
                'db_table': 'Movie',
            },
        ),
    ]
