# Generated by Django 4.2.5 on 2023-09-09 12:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_alter_movie_average_rating_out_of_five'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='average_rating_out_of_five',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, validators=[django.core.validators.DecimalValidator(decimal_places=1, max_digits=2)]),
        ),
    ]
