# Generated by Django 4.2.5 on 2023-09-19 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_movie_image_url'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='movie',
            table=None,
        ),
    ]
