name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.8
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run User Tests
      run: |
        python manage.py test user.tests
    - name: Run Movie Tests
      run: |
        python manage.py test movie.tests
    - name: Run Review Tests
      run: |
        python manage.py test review.tests

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: success()
    steps:
    - name: Deploy to Render
      uses: renderinc/deploy-to-render-action@v1
